/**
 * Constants for the restaurant analytics system
 */

export const ERROR_CODES = {
  // User Input Errors (4xx)
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_TIMEFRAME: 'INVALID_TIMEFRAME',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  AMBIGUOUS_QUERY: 'AMBIGUOUS_QUERY',
  MISSING_REQUIRED_PARAM: 'MISSING_REQUIRED_PARAM',
  PARAM_OUT_OF_RANGE: 'PARAM_OUT_OF_RANGE',

  // Transient Errors (5xx - Retryable)
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  BQ_STREAMING_BUFFER: 'BQ_STREAMING_BUFFER',
  GEMINI_QUOTA_EXCEEDED: 'GEMINI_QUOTA_EXCEEDED',
  QUERY_TIMEOUT: 'QUERY_TIMEOUT',

  // Service Degradation
  CHART_GENERATION_FAILED: 'CHART_GENERATION_FAILED',
  FORECAST_UNAVAILABLE: 'FORECAST_UNAVAILABLE',
  ANOMALY_DETECTION_SKIPPED: 'ANOMALY_DETECTION_SKIPPED',
  CONVERSATION_HISTORY_UNAVAILABLE: 'CONVERSATION_HISTORY_UNAVAILABLE',

  // Configuration Errors
  MISSING_ENV_VAR: 'MISSING_ENV_VAR',
  SECRET_NOT_FOUND: 'SECRET_NOT_FOUND',
  INVALID_SERVICE_ACCOUNT: 'INVALID_SERVICE_ACCOUNT',
  BQ_DATASET_NOT_FOUND: 'BQ_DATASET_NOT_FOUND',
  OAUTH_NOT_CONFIGURED: 'OAUTH_NOT_CONFIGURED',

  // Data Integrity
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
  INVALID_METRIC_VALUE: 'INVALID_METRIC_VALUE',
  MISSING_REQUIRED_DATA: 'MISSING_REQUIRED_DATA',
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  GEMINI_API_ERROR: 'GEMINI_API_ERROR',
} as const;

export const TIMEFRAMES = {
  TODAY: 'today',
  YESTERDAY: 'yesterday',
  THIS_WEEK: 'this_week',
  LAST_WEEK: 'last_week',
  THIS_MONTH: 'this_month',
  LAST_MONTH: 'last_month',
} as const;

export const METRICS = {
  NET_SALES: 'net_sales',
  QUANTITY_SOLD: 'quantity_sold',
} as const;

export const AGGREGATIONS = {
  SUM: 'sum',
  AVG: 'avg',
  COUNT: 'count',
  MIN: 'min',
  MAX: 'max',
} as const;

export const LOG_LEVELS = {
  DEBUG: 'DEBUG',
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL',
} as const;

export const DEFAULT_VALUES = {
  TIMEZONE: 'America/Chicago',
  CURRENCY: 'USD',
  MAX_RETRIES: 3,
  INITIAL_DELAY_MS: 1000,
  MAX_DELAY_MS: 30000,
  BACKOFF_MULTIPLIER: 2,
  JITTER_MS: 500,
  MAX_CHART_DATAPOINTS: 20,
  MAX_CONVERSATION_HISTORY: 10,
  MAX_QUERY_RESULTS: 100,
} as const;
